// Build step for the EdgeOne Pages (Git-connected) deploy of makers-wfh5gmrpw0pi.
//
// WHY THIS EXISTS
// ---------------
// The native Git deploy builds from repo root and, with an EMPTY OutputDir, copies the ENTIRE
// repo (incl. index/ ~1.5GB and index-slim/ ~152MB) into the static assets -> exceeds the build
// volume limit -> "Deploy Failed". The live domain mg.147771.xyz is bound to this project, so a
// Failed deploy means /search stays broken (503/500).
//
// This script emits a CLEAN `dist/` containing ONLY what the function/runtime needs, so the
// Git project deploys successfully while index/ + index-slim/ remain in git (served to the
// function at runtime via jsDelivr @<deploy-SHA>).
//
// It is invoked by `npm run build:pages` (configured as the project's BuildCmd). It must run
// AFTER build_ref.mjs (which writes cloud-functions/_ref.js + _ref.json with the deploy SHA).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');

// Everything we want in the deployed artifact (whitelist). Anything else (index/, index-slim/,
// node_modules/, .git/, .edgeone/, .github/, .workbuddy/, edgeone-api/, build*.mjs, scratch
// files, etc.) is intentionally excluded.
const INCLUDE = [
  'cloud-functions', // search.js, detail.js, health.js, index.js, mg.js, _ref.js, _ref.json, ...
  'package.json',
  'ys-plugin.json',
  'mg-plugin.json',
  'README.md',
];

function rmrf(p) {
  fs.rmSync(p, { recursive: true, force: true });
}

// Files inside cloud-functions/ that must NOT be shipped (dev scratch / probes).
// _ref.js / _ref.json are required (generated by build_ref.mjs) and are kept.
const CF_SKIP = new Set(['probe.js', '_bench_real.mjs', '_test_index.mjs']);

function copyEntry(srcRel) {
  const src = path.join(ROOT, srcRel);
  const dst = path.join(DIST, srcRel);
  if (!fs.existsSync(src)) {
    console.warn(`[build_pages] skip (missing): ${srcRel}`);
    return;
  }
  const st = fs.statSync(src);
  if (st.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
      const base = path.basename(entry);
      if (srcRel === 'cloud-functions' && CF_SKIP.has(base)) {
        console.log(`[build_pages] skip scratch: ${path.join(srcRel, entry)}`);
        continue;
      }
      copyEntry(path.join(srcRel, entry));
    }
  } else {
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.copyFileSync(src, dst);
  }
}

console.log('[build_pages] cleaning dist/ ...');
rmrf(DIST);
fs.mkdirSync(DIST, { recursive: true });

for (const rel of INCLUDE) {
  copyEntry(rel);
}

// Sanity checks: the runtime MUST have these.
const required = [
  'cloud-functions/search.js',
  'cloud-functions/_ref.js',
  'cloud-functions/_ref.json',
  'package.json',
  'ys-plugin.json',
  'mg-plugin.json',
];
const missing = required.filter((f) => !fs.existsSync(path.join(DIST, f)));
if (missing.length) {
  console.error('[build_pages] FATAL missing required files:', missing);
  process.exit(1);
}

// Guard: under no circumstance may the giant data dirs leak into the build output.
for (const bad of ['index', 'index-slim', 'node_modules', '.git', '.edgeone']) {
  if (fs.existsSync(path.join(DIST, bad))) {
    console.error(`[build_pages] FATAL forbidden dir present in dist/: ${bad}`);
    process.exit(1);
  }
}

// Report size + file count of the produced artifact.
let bytes = 0;
let count = 0;
(function walk(p) {
  for (const e of fs.readdirSync(p)) {
    const fp = path.join(p, e);
    const st = fs.statSync(fp);
    if (st.isDirectory()) walk(fp);
    else { bytes += st.size; count++; }
  }
})(DIST);
console.log(`[build_pages] dist/ ready: ${count} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`);
console.log('[build_pages] top-level:', fs.readdirSync(DIST).join(', '));
